version: '3.8'
services:
  redisCache:
    image: redis:alpine
    restart: always
    container_name: redisCache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${PASSWORD}
    volumes: 
      - redisCache:/data
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   restart: always
  #   ports:
  #     - "2181:2181"
  # kafka:
  #   image: wurstmeister/kafka
  #   container_name: kafka
  #   restart: always
  #   ports:
  #     - "9092:9092"
  #     - "1099:1099"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_HOST_NAME: kafka
  #     JMX_PORT: 1099
  #   depends_on:
  #     - zookeeper
  # kafka_manager:
  #   image: hlebalbau/kafka-manager:stable
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     ZK_HOSTS: zookeeper:2181
  #   command: -Dpidfile.path=/dev/null
  # frontend:
  #   container_name: frontend
  #   image: buddy22/realcode-app-frontend:latest
  #   pull_policy: always
  #   # build:
  #   #   context: ./frontend
  #   #   dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - BACKEND_URL=http://backend:8080  
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - backend
  # backend: 
  #   container_name: backend
  #   image: buddy22/realcode-app-backend:latest
  #   pull_policy: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - redisCache
  #     - zooRealcode
  #     - kafkaRealCode
  # consumer: 
  #   container_name: consumer
  #   image: buddy22/realcode-app-consumer:latest
  #   pull_policy: always
  #   # build:
  #   #   context: ./utils/kafka/consumer
  #   #   dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - redisCache
  #     - zooRealcode
  #     - kafkaRealCode
volumes:
  database_dockerizing:
  api_volume:
  redisCache:
    driver: local
  main-app:
    driver: local

networks:
  fullstack:
    driver: bridge