version: '3.8'
services:
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - BACKEND_URL=http://backend:8000/code
  # backend:
  #   container_name: backend
  #   build: ./backend
  #   volumes:
  #     - ./backend:/app/backend
  #   ports:
  #     - "8000:8000"
  #   stdin_open: true
  #   tty: true
  #   command: python3 manage.py runserver 0.0.0.0:8000
  cache:
    image: redis:alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${PASSWORD}
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local
